#!/usr/bin/sh

/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=all'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=wp'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=news'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=sport'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=finance'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=inet'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=oto'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=hot'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=wolipop'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=health'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=travel'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=food'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=20detik'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=x'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=web&channel=forum'

/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=all'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=wp'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=news'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=sport'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=finance'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=inet'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=oto'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=hot'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=wolipop'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=health'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=travel'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=food'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=android&channel=x'

/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=all'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=wp'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=news'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=sport'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=finance'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=inet'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=oto'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=hot'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=wolipop'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=health'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=travel'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=food'
/usr/bin/curl -XGET 'https://nowreport.detik.com/ga/traffics/dailypull?platform=ios&channel=x'

